import Head from "next/head";
import { useWeb3React } from "@web3-react/core";
import { injected } from "../lib/connectors";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { chainId, account, active, activate, deactivate } = useWeb3React();

  const handdleConnect = () => {
    if (active) {
      deactivate();
      return;
    }

    activate(injected, (err) => {
      if ("/No Ethereum provider was found on window.ethereum/".test(error)) {
        window.open("https://metamask.io/download.html");
      }
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Pages!</a>
        </h1>

        <p>Account: {account}</p>
        <p>chainId: {chainId}</p>
        <button type="button" onClick={handdleConnect}>
          {active ? "disconnect" : "connect"}
        </button>
      </main>
    </div>
  );
}
